// LOCALHOST
###
GET http://localhost:8080/user

### Get contact by id
GET http://localhost:8080/user/ginacampos

### Create User (default require "username and password")
POST http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "username": "mariabrown",
    "password": "brownPassword"
}

// PRODUCTION Deploy
### Get all contacts
GET https://cse341-web-server-ii.onrender.com/contacts

### Get contact by id
GET https://cse341-web-server-ii.onrender.com/contacts/65ac5f2be62521267d52698e

### Create contact
POST https://cse341-web-server-ii.onrender.com/contacts HTTP/1.1
content-type: application/json

{
    "firstName":"Rosalia",
    "lastName":"Diaz",
    "email":"rosaliadiaz@gmail.com",
    "favoriteColor":"Yellow",
    "birthday":"04/15/10"
}

### Update contact
PUT https://cse341-web-server-ii.onrender.com/contacts/65ac5f2be62521267d526990 HTTP/1.1
content-type: application/json

{
    "firstName":"Rosalia",
    "lastName":"Diaz",
    "email":"rosaliadiaz@gmail.com",
    "favoriteColor":"Yellow",
    "birthday":"04/15/10"
}

### DELETE contact
DELETE https://cse341-web-server-ii.onrender.com/contacts/65b59e79c14d2c01e91422bf HTTP/1.1